### PR TITLE
Bitbucket status update scripts

### PR DESCRIPTION
**Pull request by DrBeak1**
* adds scripts for bitbucket status updates for organizations

### CODE REVIEW

**Comment by patniko** [comment]
Thanks for the contribution @DrBeak1! Mind signing the CLA so I can merge this in?

**Comment by DrBeak1** [comment]
@DrBeak1 due to the CLA the legal team at my co needs to review it before I can sign.

**Comment by DrBeak1** [comment]
@patniko expecting to hear back from legal team on Monday. FYI

**Comment by DrBeak1** [comment]
@patniko got the green light from legal. CLA is signed.

**Comment by patniko** [comment]
Thanks @DrBeak1!

**Pull request merged**
