### PR TITLE
Created Data Sync Service Iteration Plan 

### PR DESCRIPTION
**Pull request by Zakeelm**
This PR is for iteration Plan item [#14]

### CODE REVIEW

**Comment by ahoefling** [comment]
This is a great MVP requirements spec for offline sync and I am excited to see the development out in the open. I love the fact that the initial target is CosmosDB as I have been encouraging customers to use it especially in the mobile space.

I am wondering is there going to be provider support for other database engines such as traditional SQL Server? 

When I work on a greenfield project CosmosDB is usually an easy recommendation (unless there is a cost issue). There are many projects where I don't have the luxury of being able to use CosmosDB and I am using SQL Server. While I am not personally a fan of the implementation of ZUMO using OData, I still think there needs to be a SQL Server Provider of this technology. 

I'm not sure if this is something you and the team are considering and will put notes in another PR/Issue, but I wanted to highlight my concerns.

Thanks for putting this out in the open and keep up the great work, love the products you guys are building for devs

**Comment by elamalani** [comment]
@ahoefling Thanks for sharing your feedback. We are equally excited to support a new Data Sync service that our customers would love.

We plan to support SQL Server going forward but for the MVP, our focus is on CosmosDB as a database solution. At this time, we are thinking about a replacement strategy for Azure Mobile Apps, and we’ll share additional details in an upcoming iteration plan.

We'll be open and transparent with our customers and would love to get your continued feedback on the new Data Sync service that is in the works.

**Comment by ahoefling** [comment]
Thanks for the details about the MVP!

I'm excited to see the product when it is ready for devs to take for a test drive.

**Comment by Narnain** [comment]
This is an exciting move forward and CosmosDB is a great choice for the backend.

The key scenarios I would be looking for are:
- Share the datastore with another front end application such as asp.net
- Sync to device by partition key (i.e. a tenant or user account key)
- Sync by the same key across multiple devices (different sync state per device)

**Pull request merged**
